CREATE DATABASE IF NOT EXISTS tabletennis CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tabletennis;

CREATE TABLE IF NOT EXISTS Players (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    EloRating INT NOT NULL DEFAULT 1000,
    GamesWon INT NOT NULL DEFAULT 0,
    GamesLost INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY UK_Players_Name (Name)
);

CREATE TABLE IF NOT EXISTS Games (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    WinnerId INT NOT NULL,
    LoserId INT NOT NULL,
    WinnerEloBefore INT NOT NULL,
    LoserEloBefore INT NOT NULL,
    WinnerEloAfter INT NOT NULL,
    LoserEloAfter INT NOT NULL,
    WinnerSets INT NOT NULL DEFAULT 0,
    LoserSets INT NOT NULL DEFAULT 0,
    PlayedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Games_Winner FOREIGN KEY (WinnerId) REFERENCES Players(Id) ON DELETE RESTRICT,
    CONSTRAINT FK_Games_Loser  FOREIGN KEY (LoserId)  REFERENCES Players(Id) ON DELETE RESTRICT
);
